### ISSUE TITLE
fi gives error on iTerm 2.9.20151001 + OSX Version 10.10.5 (14F27)

### ISSUE THREAD

**Issue by escherize** [LeEnno/alfred-terminalfinder#13]
When Finder has focus, calling the fi extension (Finder -> Iterm), with error logging activated via Alfred this error is logged:

    Starting debug for 'TerminalFinder'

    [INFO: alfred.workflow.input.keyword] Processing output 'alfred.workflow.action.applescript' with arg ''
    [ERROR: alfred.workflow.action.applescript] {
        NSAppleScriptErrorBriefMessage = "Expected class name but found identifier.";
        NSAppleScriptErrorMessage = "Expected class name but found identifier.";
        NSAppleScriptErrorNumber = "-2741";
        NSAppleScriptErrorRange = "NSRange: {345, 8}";
    }

**Comment by oxoxoxox** [comment]
You can look at this commit. It works fine with El Capitain. Maybe it works with Yosemite too.

https://github.com/oxoxoxox/alfred-terminalfinder/commit/71afb061ac441b2cec2ba9a7df26f6b673b1b0ad

**Comment by LeEnno** [comment]
Thx for the report. I have to make it backwards compatible. Will fix this as soon as I find some time.

**Comment by jguice** [comment]
@oxoxoxox thanks!  This works for me.

@escherize this might help with detecting whether iTerm or iTerm2 are available:  http://stackoverflow.com/questions/14297644/check-if-an-application-exists-using-applescript

Maybe try iTerm2, fall back to iTerm, then fail as usual?

Also thanks for making this. :smiley:

**Comment by LeEnno** [comment]
you may have a look at #14 in the meantime

**Comment by LeEnno** [comment]
[The newest version](https://github.com/LeEnno/alfred-terminalfinder/blob/master/TerminalFinder.alfredworkflow?raw=true) should be working with iTerm 2.9.x.
Thanks for your reports and comments.

**Comment by escherize** [comment]
Works for me. Thanks a lot @LeEnno!!
