### ISSUE TITLE
fi isn't working if I have any tab in split pane mode

### ISSUE THREAD

**Issue by philippkuehn** [LeEnno/alfred-terminalfinder#15]
If I have just one tab opened in split pane mode, the command 'fi' isn't working anymore. The new tab is showing always the default folder.

iterm version: 2.1.4

**Comment by LeEnno** [comment]
Thanks for reporting. First off, make sure you have the correct version of the workflow installed. The master branch only supports v2.9.x from now on. You may install the 2.1.x version via https://github.com/LeEnno/alfred-terminalfinder/blob/2.1.x/TerminalFinder.alfredworkflow?raw=true

Please let me know if the issue remains.

**Comment by philippkuehn** [comment]
Yes, I've got the correct version installed.

**Comment by LeEnno** [comment]
Hm, unfortunately I don't have El Capitan installed yet. So you either have do be a little patient or investigate yourself what's going on. Fire up Script Editor, paste https://github.com/LeEnno/alfred-terminalfinder/blob/2.1.x/src/fi.scpt.txt, delete the first + the last line and see what's going wrong.

You might as well ping me at [Twitter](https://twitter.com/EnnoBigBenno), if you need a little help 🇩🇪

**Comment by LeEnno** [comment]
Ok, I'm sorry. You're probably speaking of the iTerm split panes, not the OS X split view.

I will have a look. Thanks!

**Comment by philippkuehn** [comment]
Exactly! Open iterm, open a new split screen tab, go to finder, open alfred and type "fi" and you're not in your folder :/

**Comment by LeEnno** [comment]
Please download the [latest version](https://github.com/LeEnno/alfred-terminalfinder/raw/2.1.x/TerminalFinder.alfredworkflow). Issue should be fixed.
Thx for your report again.
