### ISSUE TITLE
fi do not work well when multiple finder opened

### ISSUE THREAD

**Issue by tiann** [LeEnno/alfred-terminalfinder#16]
when i open more than one finder window, the fi can not work well, maybe give a list to choose or open the most front window?

**Comment by LeEnno** [comment]
Actually it should do exactly that. Which version of iTerm do you use and what OS X version are you on?

**Comment by tiann** [comment]
Sorry, it works well.

My iTerm has two profiles, I open one iTerm profile and the other is hidden(I didn't recongise it), when i use `fi`, the windows is opened in the hidden one.
