### ISSUE TITLE
find -> iTerm don't work

### ISSUE THREAD

**Issue by atian25** [LeEnno/alfred-terminalfinder#17]
```
Starting debug for 'TerminalFinder'

[ERROR: alfred.workflow.action.applescript] {
    NSAppleScriptErrorBriefMessage = "Expected end of line but found class name.";
    NSAppleScriptErrorMessage = "Expected end of line but found class name.";
    NSAppleScriptErrorNumber = "-2741";
    NSAppleScriptErrorRange = "NSRange: {566, 6}";
}
```

**Comment by danielmai** [comment]
@atian25 Are you using the beta for iTerm 2 Version 3 that just got released? (I'm using it too and getting a similar error.)

It's most likely because this new version has backward-incompatible changes with AppleScript, as noted here: https://iterm2.com/version3.html:

> Applescript Not Backwards Compatible
> The good news is that iTerm2's Applescript makes a lot more sense than it used to. You can manipulate split panes, and scripting will receive more love and support in the future.

> The bad news is that existing Applescript won't work any more.

> The good news is that it's pretty easy to fix.

> [The new Applescript syntax is described here.](https://iterm2.com/applescript.html)

**Comment by oxoxoxox** [comment]
Maybe this issue #13 can help you

**Comment by LeEnno** [comment]
Which version of iTerm do you use, @atian25?

Please make sure you have the corresponding workflow installed:

- for version 2.9.x: https://github.com/LeEnno/alfred-terminalfinder/blob/master/TerminalFinder.alfredworkflow?raw=true
- for version 2.1.x: https://github.com/LeEnno/alfred-terminalfinder/blob/2.1.x/TerminalFinder.alfredworkflow?raw=true

**Comment by atian25** [comment]
iTerm2 (2.1.4)

@LeEnno the second link works, thanks~
