### ISSUE TITLE
finder ---> iTerm failed

### ISSUE THREAD

**Issue by johnwatsondev** [LeEnno/alfred-terminalfinder#18]
Environment:
OS X EI Capitan    Version: 10.11.3
Alfred 2    Version: 2.8.2
iTerm2    Build 2.1.4

I used [custom-iterm-applescripts-for-alfred](https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred) for fixing iTerm integration with Alfred 2.

I have installed branch 2.1.x 's workflow but it opened Terminal with the correct path. Here is a snapshot:

![2016-03-08 22 43 33](https://cloud.githubusercontent.com/assets/12760754/13604788/5c4fe9c8-e57f-11e5-84cb-d61363221726.jpg)

@LeEnno Please let me know if I missed something or needing more detail and log. Thanks very much!

**Comment by LeEnno** [comment]
> I used custom-iterm-applescripts-for-alfred for fixing iTerm integration with Alfred 2.

AFAIK this shouldn't matter because the workflow doesn't open terminals via Alfred, but via custom scripts.

> I have installed branch 2.1.x 's workflow but it opened Terminal with the correct path.

So if I get this correctly, you use the keyword `fi` but it opens Terminals instead of iTerm?

**Comment by johnwatsondev** [comment]
@LeEnno Sorry, I checked again. It caused by my silly mistake. I typed `ft` last night. :crying_cat_face:
