### ISSUE TITLE
Not work with iTerm version 3.0

### ISSUE THREAD

**Issue by xiocode** [LeEnno/alfred-terminalfinder#19]
Alfred 2 latest version
alfred-terminalfinder version 1.6.0

User Keyword  fi

Starting debug for 'Terminal Finder v1.6.0'

[ERROR: alfred.workflow.action.applescript] {
    NSAppleScriptErrorBriefMessage = "Expected class name but found identifier.";
    NSAppleScriptErrorMessage = "Expected class name but found identifier.";
    NSAppleScriptErrorNumber = "-2741";
    NSAppleScriptErrorRange = "NSRange: {417, 8}";
}

**Comment by gaivoronsky** [comment]
@xiocode  I think you need update alfred-terminalfinder workflow

**Comment by LeEnno** [comment]
Seems like iTerm finally bumped their version number the way they should have done from the beginning.
I will have a look, thx for your report.

**Comment by davegotz** [comment]
I was having the same issue.  However, after updating to the latest version of this workflow everything worked again.

**Comment by LeEnno** [comment]
Ok, sorry everybody for the confusion. Indeed you just have to update to the workflow's latest version, @xiocode. Works totally fine with version 3.x. I changed the readme to reflect that accordingly.

Thank you, everyone.
