### ISSUE TITLE
'ft' works, but 'fi' not working!!

### ISSUE THREAD

**Issue by sinceow** [LeEnno/alfred-terminalfinder#20]
I've used the lastest workflow.
> iTerm2: build 3.0.2
> Alfred: 2.8.4

'fi' still not working!

**Comment by LeEnno** [comment]
I'm running OS X 10.11.5 with iTerm 3.0.3 and Alfred 3.0.2, all ok.
What exactly doesn't work for you??

**Comment by lufeihaidao** [comment]
```
[ERROR: alfred.workflow.action.applescript] {
    NSAppleScriptErrorBriefMessage = "Expected class name but found identifier.";
    NSAppleScriptErrorMessage = "Expected class name but found identifier.";
    NSAppleScriptErrorNumber = "-2741";
    NSAppleScriptErrorRange = "NSRange: {391, 8}";
}
```

Not work for 2.1.x version.

**Comment by LeEnno** [comment]
For iTerm version 2.1.x please use https://github.com/LeEnno/alfred-terminalfinder/raw/2.1.x/TerminalFinder.alfredworkflow

**Comment by jokefaker** [comment]
Same issue , using iTerm 3.0.4 , OSX 10.11.5 , Alfred 3.0.2

**Comment by LeEnno** [comment]
Are you using the current workflow? https://github.com/LeEnno/alfred-terminalfinder/blob/master/TerminalFinder.alfredworkflow?raw=true

**Comment by jokefaker** [comment]
Yes, I'm using the last version.
But I copy the script to the Script Editor, it works, after that 'fi' works again....I don't know why...

**Comment by LeEnno** [comment]
Mabe some caching issue? I don't know.
So now it works? Or is it just fixed temporarily?

**Comment by jokefaker** [comment]
Now it works :]

**Comment by LeEnno** [comment]
That's weird, but hey. Resolved issues are my favorite thing in the world :)
I will close this for now.
If the issue arises again, feel free to reopen it, dear issue reader.
