### ISSUE TITLE
ft does not always open current finder window

### ISSUE THREAD

**Issue by luwes** [LeEnno/alfred-terminalfinder#22]
Many times the current finder window does not get reflected in the terminal.
It will just be the current user folder ~.

This is the output of the Alfred debugger.

![schermafbeelding 2016-10-14 om 20 35 49](https://cloud.githubusercontent.com/assets/360826/19398710/3fbee67a-924e-11e6-8b23-bebda38b31d2.png)

**Comment by LeEnno** [comment]
Thanks for the report. I have never been experiencing anything like that. Do you have a way to reliably reproduce the behavior?

On Fr., Okt. 14, 2016 at 8:39 PM, wesley luyten <notifications@github.com> wrote:
Many times the current finder window does not get reflected in the terminal.
It will just be the current user folder ~.

This is the output of the Alfred debugger.

[https://cloud.githubusercontent.com/assets/360826/19398710/3fbee67a-924e-11e6-8b23-bebda38b31d2.png]

**Comment by luwes** [comment]
Thanks for the quick reply. I use this workflow all the time, it's really great except this little thing that's bugging me now. No, I can't reproduce it consistently. It's random. Here's a screenvid, http://recordit.co/m84iH1UXhQ

**Comment by LeEnno** [comment]
Thanks a lot. I will try to reproduce it.
Which macOS version are you on?

On Fr., Okt. 14, 2016 at 8:55 PM, wesley luyten <notifications@github.com> wrote:
Thanks for the quick reply. I use this workflow all the time, it's really great except this little thing that's bugging me now. No, I can't reproduce it consistently. It's random. Here's a screenvid, http://recordit.co/m84iH1UXhQ [http://recordit.co/m84iH1UXhQ]

**Comment by luwes** [comment]
macOS Sierra

**Comment by luwes** [comment]
I rewrote the apple script a bit. It's working on my end now but I'm not really sure why this one does and the other doesn't.

```
on alfred_script(q)
  tell application "Finder"
    set pathList to (quoted form of POSIX path of (folder of the front window as alias))
  end tell
  
  set new_term to 0
  tell application "System Events"
    if "Terminal" is not in name of processes then
      set new_term to 1
    end if
  end tell

  tell application "Terminal"
    activate
    if new_term is 0 then
      tell application "System Events" to keystroke "t" using command down
    end if
    do script ("cd " & pathList) in first window
  end tell
end alfred_script
```

**Comment by LeEnno** [comment]
I updated the workflow. Check if this fixes your issues. It did on my site.
