### ISSUE TITLE
Alfred crashes when using terminalfinder

### ISSUE THREAD

**Issue by jordibruin** [LeEnno/alfred-terminalfinder#24]
For some reason Alfred crashes whenever I use terminalfinder in the last few days. Does anyone else have the same issue?

**Comment by LeEnno** [comment]
Still the case? Which OS version do you run on?

**Comment by jordibruin** [comment]
Hi LeEnno, it hasn't happened for a while now. I'm on Mojave, but I think it was something wrong in a previous Alfred version. Thanks for the reply!
