### ISSUE TITLE
[Bug] Finder->Terminal/iTerm not working on macOS Catalina

### ISSUE THREAD

**Issue by tillchen** [LeEnno/alfred-terminalfinder#27]
Hi!

When I tried to use `fi` or `ft` to open the current finder path in Terminal/iTerm, the generated command is `clear; cd '/Users/tillchen/Downloads:/'`, which is actually an invalid path due to the colon at the end. I guess this might be caused by the change of macOS Catalina?

Thank you!

**Comment by onevcat** [comment]
Same here.

**Comment by LeEnno** [comment]
Thanks for reporting 👍

This seems to be either a bug on Apple's side or a weird decision to include that colon all of a sudden.

Is this happening to _all_ paths or just special ones like Downloads, Desktop, Documents, etc? You may run this script in the editor to check:

```applescript
tell application "Finder"
	return (quoted form of POSIX path of (folder of the front window as alias))
end tell
```

**Comment by tillchen** [comment]
@LeEnno Thank you for replying:)

I just checked. And I believe this is indeed happening for ***all*** paths. Maybe it is Apple to blame for this issue 😆 .

**Comment by LeEnno** [comment]
Maybe. Googling around I don’t find very much regarding this issue. Let’s wait to the final release. Once this change becomes more apparent to the public hopefully we get a fix (or an explanation).

**Comment by tillchen** [comment]
Sure:)

**Comment by Hurray0** [comment]
My command works on the default terminal, but not work on iTerm.
System: Catalina 10.15
iTerm: Build 3.3.5beta2

**Comment by tillchen** [comment]
I just tried again with the official version of Catalina. And it looks like the problem is resolved by Apple:D!
