### ISSUE TITLE
How to open Arrangement fast？

### ISSUE THREAD

**Issue by cyh41** [LeEnno/alfred-terminalfinder#29]

**Comment by LeEnno** [comment]
Would you mind explaining what you‘re referring to?

**Comment by cyh41** [comment]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/19506560/71063377-8e5dfa00-21a7-11ea-9c5e-921b73811852.png">

**Comment by LeEnno** [comment]
Sorry, it’s hard for me to find out what you’re getting at.

**Comment by LeEnno** [comment]
I don’t know how to help in this case so I‘m closing this for now.
