### ISSUE TITLE
Use iTerm instead of Default Terminal app

### ISSUE THREAD

**Issue by t-ober** [LeEnno/alfred-terminalfinder#34]
First of all thanks for this very helpful Workflow 🙂  

Can somebody help me out in setting `iTerm` as the Terminal app to use? 
Do I have to manually adjust the `NSAppleScript` or set any other option I am not aware of?

**Comment by LeEnno** [comment]
Thanks for your kind words. Would you mind giving a little more details regarding what you are trying to do?

In general `fi` and `if` keywords should work with iTerm out of the box. What exactly does not work for you? What Alfred and macOS version are you using?

**Comment by t-ober** [comment]
Alright this was totally my bad. How about engaging in a little reading next time .. I was not aware that there are different commands for using iterm. Now magically it works 😂 Had the known `fi` issue but that could also be resolved with reentering and saving the script. Thanks for the pointer!
