### ISSUE TITLE
Add Warp support?

### ISSUE THREAD

**Issue by luwes** [LeEnno/alfred-terminalfinder#35]
`open -a Warp.app $(osascript -e 'tell application "Finder" to get the POSIX path of (target of front window as alias)')`

**Comment by LeEnno** [comment]
I’m not using this workflow anymore. So investing any time to add features will probably not happen. But I’m happy to accept Pull Requests.

**Comment by luwes** [comment]
👍 All good, I added it manually. Might still be useful for others to find the command here.

**Comment by ChrisZou** [comment]
@luwes Might better add quotes to deal with paths containing space character: `open -a Warp.app "$(osascript -e 'tell application "Finder" to get the POSIX path of (target of front window as alias)')"`
