### ISSUE TITLE
Error on using "fi"

### ISSUE THREAD

**Issue by milosmatic** [LeEnno/alfred-terminalfinder#6]
This error occurs when using "fi" command

    [ERROR: alfred.workflow.action.applescript] {
        NSAppleScriptErrorBriefMessage = "Expected class name but found identifier.";
        NSAppleScriptErrorMessage = "Expected class name but found identifier.";
        NSAppleScriptErrorNumber = "-2741";
        NSAppleScriptErrorRange = "NSRange: {417, 8}";
    }

**Comment by jothirams** [comment]
I’m using iTerm 2.0 and for me it is not working. I tried your above script, and also added

`		display dialog pathList`

And this displays correctly. However, the "cd" text is not sent to the iTerm.

**Comment by LeEnno** [comment]
A few questions:

1. Which version of OS X and iTerm do you use?
2. What happens instead? Does iTerm open? Does it come to the front? Does the script display any errors?

**Comment by jothirams** [comment]
@LeEnno 

1. OSX 10.10.2  - iTerm 2.0 (from About)
2. iTerm opens and comes to the front, the script does not throw any error. It is just that the "cd" & pathList => command is not executed on iTerm.

**Comment by LeEnno** [comment]
That's weird. What happens when executing the following script?

```applescript
tell application "iTerm"
	tell (make new terminal)
		set pathList to "~/Documents"
		tell (launch session "Default") to write text "cd " & pathList
	end tell
end tell
```

**Comment by jothirams** [comment]
Hello, this works now.. also your Alfred extension works.. Not sure what the problem was though..

**Comment by LeEnno** [comment]
Well, I love problems which solve themselves.
I will close this issue for now. Feel free to reopen if necessary.
