### ISSUE TITLE
Pathfinder to iTerm not working

### ISSUE THREAD

**Issue by nogorilla** [LeEnno/alfred-terminalfinder#9]
Using `PI` shortcut to open current Pathfinder location in iTerm is no longer functioning correctly.  It will open iTerm, however, it will not apply the expected path

**Comment by LeEnno** [comment]
Thx for your report. Unfortunately I didn't do the work for the Path Finder parts of the script myself. I'm also not a Path Finder user, so I can't test it.
Perhaps the original author of the relevant script – @olibob – may be able to help.
